name: My First Workflow
on: 
  push:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: java version 
        run: java -version
      - name: maven version
        run: mvn --version
      - name: docker version
        run: docker -v
      - name: git version
        run: git --version
      - name: python version
        run: python -v
        
    
